MVC5开发框架/code/webSite/Areas/admin/Controllers/af_AuditFlowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web.Controllers;

namespace web.Areas.admin.Controllers
{
    public class af_AuditFlowController : baseController
    {
        //搜索数据
        public ActionResult Select(db.view.af_AuditFlow model)
        {
            model.Search();
            if (rui.requestHelper.isAjax())
                return PartialView("_showData", model);
            return View(model);
        }

        //展示详情
        public ActionResult Detail(string rowID)
        {
            db.af_AuditFlow model = db.bll.af_AuditFlow.getEntryByRowID(rowID, dc);
            model.auditTypeCode = db.bll.af_AuditType.getNameByCode(model.auditTypeCode, dc);
            model.orgCode = db.bll.sbs_Org.getNameByCode(model.orgCode, dc);
            return View(model);
        }

        //展示新增
        [HttpGet]
        public ActionResult Insert()
        {
            db.af_AuditFlow model = new db.af_AuditFlow();
            return View(model);
        }

        //保存新增
        [HttpPost]
        public JsonResult Insert(db.af_AuditFlow model)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                if (ModelState.IsValid)
                {  
                    string rowID = db.bll.af_AuditFlow.insert(model, dc);
                    result.data = rui.jsonResult.getAJAXResult("新增成功", true, 
                        rui.jsonResult.getDicByRowID(rowID));
                }
                else
                {
                    result.data = rui.jsonResult.getAJAXResult("输入不合法", false);
                }
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //展示更新
        [HttpGet]
        public ActionResult Update(string rowID)
        {
            db.af_AuditFlow model = db.bll.af_AuditFlow.getEntryByRowID(rowID, dc);
            return View(model);
        }

        //保存更新
        [HttpPost]
        public JsonResult Update(db.af_AuditFlow model)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                if (ModelState.IsValid)
                {
                    db.bll.af_AuditFlow.update(model, dc);
                    result.data = rui.jsonResult.getAJAXResult("更新成功", true);
                }
                else
                {
                    result.data = rui.jsonResult.getAJAXResult("输入不合法", false);
                }
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //删除
        [HttpPost]
        public JsonResult Delete(string rowID)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                string keyCode = db.bll.af_AuditFlow.getKeyByRowID(rowID,dc);
                db.bll.af_AuditFlow.delete(keyCode, dc);
                result.data = rui.jsonResult.getAJAXResult("删除成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //启用
        public JsonResult Enable(string keyFieldValues)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                string msg= db.bll.af_AuditFlow.toUse(keyFieldValues,dc);
                result.data = rui.jsonResult.getAJAXResult(msg, true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //禁用
        public JsonResult Disable(string keyFieldValues)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                 string msg = db.bll.af_AuditFlow.toNoUse(keyFieldValues,dc);
                 result.data = rui.jsonResult.getAJAXResult(msg, true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //审批流设计 - 以前有，则打开编辑，没有则新增
        [HttpGet]
        public ActionResult Design(string rowID)
        {
            db.view.af_AuditFlowDesign model = new db.view.af_AuditFlowDesign();
            model.rowID = rowID.ToString();
            model.opMode = db.bll.af_AuditFlow.hasNode(rowID,dc) ? "update" : "insert";
            if(model.opMode == "update")
            {
                Dictionary<string, string> dic = db.bll.af_AuditFlow.getWFJson(rowID, dc);
                model.begin = dic["begin"];
                model.end = dic["end"];
                model.actives = dic["actives"];
                model.routes = dic["routes"];
            }
            return View(model);
        }

        //选中节点（展示节点编辑分部视图）
        [HttpGet]
        public ActionResult SelectNode(string nodeID)
        {
            db.af_AuditNode model = db.bll.af_AuditNode.getEntryByCode(nodeID, dc);
            return PartialView("SelectNode", model);
        }

        //保存选中节点
        [HttpPost]
        public JsonResult SelectNode(db.af_AuditNode model)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.af_AuditNode.update(model, dc);
                result.data = rui.jsonResult.getAJAXResult("成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //选中路由（展示路由编辑分部视图）
        [HttpGet]
        public ActionResult SelectRoute(string nodeID)
        {
            db.af_NodeRelation model = db.bll.af_NodeRelation.getEntryByCode(nodeID, dc);
            return PartialView("SelectRoute", model);
        }

        //保存选中路由
        [HttpPost]
        public JsonResult SelectRoute(db.af_NodeRelation model)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.af_NodeRelation.update(model, dc);
                result.data = rui.jsonResult.getAJAXResult("成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //创建开始和结束节点
        public JsonResult createStartAndEnd(string rowID,string startID,string endID)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.af_AuditNode.createStartAndEnd(rowID, startID, endID, dc);
                result.data = rui.jsonResult.getAJAXResult("no:成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //创建活动节点（节点编号）
        public JsonResult createNode(string rowID,string guidID)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.af_AuditNode.createNode(rowID, guidID,dc);
                result.data = rui.jsonResult.getAJAXResult("no:成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //创建路由（路由编号，开始，结束）
        public JsonResult createRoute(string rowID, string guidID, string startID, string endID)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.af_AuditNode.createRoute(rowID, guidID, startID, endID, dc);
                result.data = rui.jsonResult.getAJAXResult("no:成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //移除元素（元素编号，类型）
        public JsonResult dropElement(string rowID,string guidID,string type)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.af_AuditNode.dropElement(rowID, guidID, type, dc);
                result.data = rui.jsonResult.getAJAXResult("no:成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //审批流结果保存
        [HttpPost]
        public JsonResult saveJson(string rowID, string startJson, string activeJsons, string routeJsons, string endJson)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.af_AuditNode.saveJson(rowID, startJson, activeJsons, routeJsons, endJson, dc);

MVC5开发框架/code/webSite/Areas/admin/Views/af_AuditFlow/Design.cshtml
@model db.view.af_AuditFlowDesign
@{
    ViewBag.Title = "审批流设计";
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/content/layui/css/layui.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/css/rui.layout.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/content/fontawesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/fontawesome/css/rui.button.css")" rel="stylesheet" type="text/css" />

    @*jquery*@
    <script type="text/javascript" src=@Url.Content("~/Content/scripts/jquery-1.12.4.min.js"+rui.configHelper.ctxKey)></script>
    @*easyUI*@
    <link href="@Url.Content("~/content/easyui/icon.css"+rui.configHelper.ctxKey)" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/easyui/bootstrap/easyui.css"+rui.configHelper.ctxKey)" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="@Url.Content("~/content/easyui/jquery.easyui.js"+rui.configHelper.ctxKey)"></script>
    @*layui*@
    <script type="text/javascript" src="@Url.Content("~/content/layui/layui.js"+rui.configHelper.ctxKey)"></script>
    <script type="text/javascript" src="@Url.Content("~/content/scripts/jquery.wfdesigner.js"+rui.configHelper.ctxKey)"></script>
    @*自定义的js*@
    <script type="text/javascript" src="@Url.Content("~/content/scripts/rui.tools.js"+rui.configHelper.ctxKey)"></script>
    <script type="text/javascript" src="@Url.Content("~/content/fontawesome/rui.button.js"+rui.configHelper.ctxKey)"></script>
    <script type="text/javascript" src="@Url.Content("~/content/scripts/rui.modelDialog.js"+rui.configHelper.ctxKey)"></script>

    <script type="text/javascript">
        var opMode = '@Model.opMode';
        var rowID = '@Model.rowID';

        //绘制审批流 -- 修改模式下调用
        function showWF() {
            //info("showWF");
            var jsondata = function (begin, actives, routes, end) {
                this.begin = begin;
                this.activeArray = actives;
                this.routeArray = routes;
                this.end = end;
            }
            var begin = '@Html.Raw(Model.begin)';
            var end = '@Html.Raw(Model.end)';
            var ats = '@Html.Raw(Model.actives)';
            var atArray = ats.split("*");
            var ro = '@Html.Raw(Model.routes)';
            var rtArray = ro.split("*");
            var jsdata = new jsondata(begin, atArray, rtArray, end);
            $("#wf").draw({ dbmousefunction: "select", jsondata: jsdata, rowID: rowID });
        }

        //保存JSon数据
        function saveJson(reflesh) {
           //info("saveJson");
            //获取数据
            var wfjson = $("#wf").getJson();
            if (wfjson) {
                //------------遍历活动节点
                var acts = "";
                for (var i = 0; i < wfjson.activeArray.length; i++) {
                    acts += wfjson.activeArray[i] + "*";
                }
                if (acts.length > 0)
                    acts = acts.substr(0, acts.length - 1);
                //------------遍历路由节点
                var routes = "";
                for (var i = 0; i < wfjson.routeArray.length; i++) {
                    routes += wfjson.routeArray[i] + "*";
                }
                if (routes.length > 0)
                    routes = routes.substr(0, routes.length - 1);

                //展示数据
                //info("起始点的json数据：" + wfjson.begin + "\n\r活动节点数据：" + acts + "\n\r路由数据：" + routes + "\n\r终结点的json数据：" + wfjson.end);
            }
            //提交服务器
            ajaxPost("saveJson", { rowID: rowID, startJson: wfjson.begin, activeJsons: acts, routeJsons: routes, endJson: wfjson.end }, function (data) {
                showJsonResult(data, function () {
                    if (reflesh == true)
                        location.reload();
                });
            });
            $("#wf").buildJson();
        }

        //文档加载完毕
        $(document).ready(function () {
            //设置wf的高度
            var height = $(document).height();
            $("#wf").height(height - 38);
            if (opMode == "insert") {
                //绘制流程图(传入rowID信息)
                $("#wf").draw({ dbmousefunction: "select", rowID: rowID });
            }
            if (opMode == "update") {
                showWF(rowID);
            }
            //新增节点
            $("#addBtn").click(function () {
                $("#wf").createActive();
                return false;
            });
            //删除元素
            $("#delBtn").click(function () {
                $("#wf").deleteElement();
                $("#wfEdit").html("");
                return false;
            });
            //保存，获取所有元素的json数据
            $("#saveBtn").click(function () {
               //info("1");
                saveJson(false);
                return false;
            });
            //刷新工作流
            $("#refleshBtn").click(function () {
                saveJson(true);
                return false;
            });
            //选择用户
            $("#wfEdit").on("click", "#selectUser", function () {
                console.info("wwww");
                var selected = $("#auditUserCode").val();
                openDialog("选择用户", "/admin/af_AuditFlow/LinkUsers?upCode=auditUserCode&upName=auditUserName&selected=" + selected,window,"type1",false);
            });
        });
    </script>
</head>
<body>
    <div style="height: 25px; line-height: 25px; margin-bottom: 2px;">
        <a id="addBtn" class="opBtn">新增活动节点</a>
        <a id="delBtn" class="opBtn">删除选择项</a>
        <a id="saveBtn" class="opBtn">保存工作流</a>
        <a id="refleshBtn" class="opBtn">刷新节点名</a>
    </div>
    <div>
        <div id="wf" style="width: 49%; float: left; position: relative;"></div>
        <div id="wfEdit" style="width: 49%; float: right;"></div>
    </div>
</body>
</html>

MVC5开发框架/code/webSite/Areas/admin/Views/af_AuditFlow/Detail.cshtml
@model db.af_AuditFlow

@{
    ViewBag.Title = "Detail";
}

<div class="dialog">
    <div class="display-label hide">
        @Html.DisplayNameFor(model => model.rowID)
    </div>
    <div class="display-field hide">
        @Html.DisplayFor(model => model.rowID)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.flowCode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.flowCode)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.flowName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.flowName)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.auditTypeCode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.auditTypeCode)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.isUse)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.isUse)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.orgCode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.orgCode)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.remark)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.remark)
    </div>

    <p class="button">
        <a class="opClose">关闭</a>
    </p>
</div>

MVC5开发框架/code/webSite/Areas/admin/Views/af_AuditFlow/Insert.cshtml
@model db.af_AuditFlow

@{
    ViewBag.Title = "Insert";
}

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <div class="dialog">
        <div class="editor-label hide">
            @Html.LabelFor(model => model.rowID)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.rowID)
            @Html.ValidationMessageFor(model => model.rowID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.flowCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.flowCode)
            @Html.ValidationMessageFor(model => model.flowCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.flowName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.flowName)
            @Html.ValidationMessageFor(model => model.flowName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.auditTypeCode)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(a=>a.auditTypeCode,db.bll.af_AuditType.bindDdl())
            @Html.ValidationMessageFor(model => model.auditTypeCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.isUse)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(a=>a.isUse,rui.listHelper.bind是否(false,"否"))
            @Html.ValidationMessageFor(model => model.isUse)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.orgCode)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(a => a.orgCode, db.bll.sbs_Org.bindDdl())
            @Html.ValidationMessageFor(model => model.orgCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.remark)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.remark)
            @Html.ValidationMessageFor(model => model.remark)
        </div>

        <p class="button">
            <a class="billSave opSave" data-close="true">保存</a>
            <a class="opClose">关闭</a>
        </p>
    </div>
}

MVC5开发框架/code/webSite/Areas/admin/Views/af_AuditFlow/SelectNode.cshtml
@model db.af_AuditNode

@{
    ViewBag.Title = "选中节点";
}

@using (Html.BeginForm("SelectNode", "af_AuditFlow",FormMethod.Post,new {  id = "nodeForm"}))
{
    @Html.ValidationSummary(true)

    <div class="dialog two">
        <div class="editor-label hide">
            @Html.LabelFor(model => model.rowID)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.rowID)
            @Html.ValidationMessageFor(model => model.rowID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.flowCode)
        </div>
        <div class="editor-field">
            @db.bll.af_AuditFlow.getNameByCode(Model.flowCode,null)
            @Html.HiddenFor(model => model.flowCode)
            @Html.ValidationMessageFor(model => model.flowCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.nodeCode)
        </div>
        <div class="editor-field read">
            @Html.EditorFor(model => model.nodeCode)
            @Html.ValidationMessageFor(model => model.nodeCode)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.nodeJson)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.nodeJson)
            @Html.ValidationMessageFor(model => model.nodeJson)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.nodeDesc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nodeDesc)
            @Html.ValidationMessageFor(model => model.nodeDesc)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.nodeType)
        </div>
        <div class="editor-field hide">
            @db.bll.af_AuditNode.tranfer("nodeType",Model.nodeType)
            @Html.HiddenFor(model=>model.nodeType)
            @Html.ValidationMessageFor(model => model.nodeType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.passType)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(a => a.passType, rui.listHelper.bind审批通过方式())
            @Html.ValidationMessageFor(model => model.passType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.printTag)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(a=>a.printTag,db.bll.af_AuditPost.bindDdlForPrintTag())
            @Html.ValidationMessageFor(model => model.printTag)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.auditUserCodes)
        </div>
        <div class="editor-field">
            <span id="auditUserName">@db.bll.rbac_User.getNamesByCodes(Model.auditUserCodes,db.efHelper.newDc())</span>
            @Html.HiddenFor(a => a.auditUserCodes, new { id="auditUserCode" })
            @Html.ValidationMessageFor(model => model.auditUserCodes)
            <span class="btn" id="selectUser">选择用户</span>
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.auditRoleCodes)
        </div>
        <div class="editor-field hide">
            @Html.DropDownListFor(model => model.auditRoleCodes,db.bll.rbac_Role.bindDdl(true))
            @Html.ValidationMessageFor(model => model.auditRoleCodes)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.auditPostCodes)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(a => a.auditPostCodes, db.bll.af_AuditPost.bindDdl(true))
            @Html.ValidationMessageFor(model => model.auditPostCodes)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.selectUserCodes)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.selectUserCodes)
            @Html.ValidationMessageFor(model => model.selectUserCodes)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.selectRoleCodes)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.selectRoleCodes)
            @Html.ValidationMessageFor(model => model.selectRoleCodes)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.selectPostCodes)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.selectPostCodes)
            @Html.ValidationMessageFor(model => model.selectPostCodes)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.isNoteInform)
        </div>
        <div class="editor-field hide">
            @Html.DropDownListFor(a => a.isNoteInform, rui.listHelper.bind是否(false, "否"))
            @Html.ValidationMessageFor(model => model.isNoteInform)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.isEmailInform)
        </div>
        <div class="editor-field hide">
            @Html.DropDownListFor(a => a.isEmailInform, rui.listHelper.bind是否(false, "否"))
            @Html.ValidationMessageFor(model => model.isEmailInform)
        </div>

        <p class="button">
            <a class="billSave btn" data-close="true"><i class='fa fa-asterisk'></i>&nbsp;保存</a>
        </p>
    </div>
}

<script type="text/javascript">
    $(".billSave").click(function () {
        console.info($("#nodeForm").serialize());
        var value = getDisabledValue($("#nodeForm"));
        $.ajax({
            type: "post",
            dataType: "json",
            url: "/admin/af_AuditFlow/SelectNode",
            data: $("#nodeForm").serialize() + value,
            success: function (data) {
                showInfo("保存成功");
            },
            error: function (data) {
                alert("ajax请求出错" + data);
            }
        })
    });
</script>    

MVC5开发框架/code/webSite/Areas/admin/Views/af_AuditFlow/SelectRoute.cshtml
@model db.af_NodeRelation

@{
    ViewBag.Title = "SelectRoute";
}

@using (Html.BeginForm("SelectRoute", "af_AuditFlow", FormMethod.Post, new { id = "nodeForm" }))
{
    @Html.ValidationSummary(true)

    <div class="dialog two">
        <div class="editor-label hide">
            @Html.LabelFor(model => model.rowID)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.rowID)
            @Html.ValidationMessageFor(model => model.rowID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.flowCode)
        </div>
        <div class="editor-field">
            @db.bll.af_AuditFlow.getNameByCode(Model.flowCode, db.efHelper.newDc())
            @Html.HiddenFor(model => model.flowCode)
            @Html.ValidationMessageFor(model => model.flowCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.startNodeCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.startNodeCode)
            @Html.ValidationMessageFor(model => model.startNodeCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.endNodeCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.endNodeCode)
            @Html.ValidationMessageFor(model => model.endNodeCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.passExpression)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.passExpression)
            @Html.ValidationMessageFor(model => model.passExpression)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.nodeGuid)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.nodeGuid)
            @Html.ValidationMessageFor(model => model.nodeGuid)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.nodeJson)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.nodeJson)
            @Html.ValidationMessageFor(model => model.nodeJson)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.remark)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.remark)
            @Html.ValidationMessageFor(model => model.remark)
        </div>

        <p class="button">
            <a class="billSave btn" data-close="true"><i class='fa fa-asterisk'></i>&nbsp;保存</a>
        </p>
    </div>
}

<script type="text/javascript">
    $(".billSave").click(function () {
        var value = getDisabledValue($("#nodeForm"));
        $.ajax({
            type: "post",
            dataType: "json",
            url: "/admin/af_AuditFlow/SelectRoute",
            data: $("#nodeForm").serialize() + value,
            success: function (data) {
                showInfo("保存成功");
            },
            error: function (data) {
                alert("ajax请求出错" + data);
            }
        })
    });
</script>