MVC5开发框架/code/webSite/Areas/admin/Controllers/rbac_ResourceOpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web.Controllers;


namespace web.Areas.admin.Controllers
{
    public class rbac_ResourceOpController : baseController
    {
        public ActionResult SelectPartial(db.view.rbac_ResourceOp model)
        {
            model.Search();
            if (rui.requestHelper.isAjax())
                return PartialView("_ShowData" + model.opMode, model);
            return PartialView("SelectPartial", model);
        }

        //通过勾选维护行
        [HttpPost]
        public JsonResult InsertFromCheck(string resourceCode,string opCode,string tag)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                if (tag == "true")
                {
                    db.bll.rbac_ResourceOp.insert(resourceCode, opCode, dc);
                    result.data = rui.jsonResult.getAJAXResult("no:新增成功", true);
                }
                if(tag == "false")
                {
                    db.bll.rbac_ResourceOp.delete(resourceCode, opCode, dc);
                    result.data = rui.jsonResult.getAJAXResult("no:删除成功", true);
                }
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //新增行
        [HttpPost]
        public JsonResult Insert(string resourceCode)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.rbac_ResourceOp.insert(resourceCode, dc);
                result.data = rui.jsonResult.getAJAXResult("no:新增成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //删除
        [HttpPost]
        public JsonResult Delete(string rowID)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.rbac_ResourceOp.delete(rowID, dc);
                result.data = rui.jsonResult.getAJAXResult("no:删除成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }
    }
}

MVC5开发框架/code/webSite/Areas/admin/Views/rbac_ResourceOp/SelectPartial.cshtml
@model db.view.rbac_ResourceOp
@{
    ViewBag.Title = "资源维护操作";
}

<style type="text/css">
</style>
<script type="text/javascript">
    //刷新当前页面的数据
    function refleshData(exeCountSql) {
        $("#container").pager("reflesh", exeCountSql);
    }
    //初始化分页
    $(function () {
        $("#container").pager();
    });
</script>

@{ string ctrl = ViewContext.RouteData.Values["controller"].ToString(); }
<div class="container" id="container" data-width="@Model.PageWidth" data-url="/admin/rbac_ResourceOp/SelectPartial">
    <div class="search">
        <span>@Html.HiddenFor(a => a.upCode)</span>
        <span>@Html.HiddenFor(a => a.opMode)</span>
    </div>
    <div class="pager"></div>
    <div class="showData ">
        @{Html.RenderPartial("_ShowData" + Model.opMode);}
    </div>
</div>

MVC5开发框架/code/webSite/Areas/admin/Views/rbac_ResourceOp/_ShowDataDetail.cshtml
@*数据展示的公用视图*@
@model rui.pagerBase
@{ 
    string ctrl = ViewContext.RouteData.Values["controller"].ToString();
    rui.dbTools.removeShowColumn(Model.showColumn, "操作");
}
<input type="hidden" class="pagerinfo" data-rowcount="@Model.RowCount" data-pagesize="@Model.PageSize"
       data-pageindex="@Model.PageIndex" data-pagecount="@Model.PageCount"
       data-orderfield="@Model.OrderField" data-orderway="@Model.OrderWay" />
<table>
    <thead>
        <tr>
            @foreach (System.Data.DataRow row in Model.showColumn.Rows)
            {
                string colName = row["fieldCode"].ToString();
                if (row["isOrder"].ToString() == "True")
                {
                    <th data-option="@row["optionValue"]" data-field="@row["fieldCode"]" data-order="@Model.OrderWay">@row["fieldName"]@Html.orderColumn(Model.OrderField, Model.OrderWay, row["fieldCode"].ToString())</th>
                }
                else
                {
                    <th data-option="@row["optionValue"]">@row["fieldName"]</th>
                }
            }
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.dataTable.Rows.Count; i++)
        {
            string rowID = Model.dataTable.Rows[i]["rowID"].ToString();
            string keyCode = Model.dataTable.Rows[i][Model.keyField].ToString();
            <tr data-code="@keyCode">
                @foreach (System.Data.DataRow row in Model.showColumn.Rows)
                {
                    string colName = row["fieldCode"].ToString();
                    if (colName == "操作")
                    {
                        <td class="opRow">
                        </td>
                    }
                    else
                    {
                        <td>@Model.dataTable.Rows[i][colName]</td>
                    }
                }
            </tr>
        }
    </tbody>
</table>

MVC5开发框架/code/webSite/Areas/admin/Views/rbac_ResourceOp/_ShowDataUpdate.cshtml
@*数据展示的公用视图*@
@model rui.pagerBase
@{ string ctrl = ViewContext.RouteData.Values["controller"].ToString(); }
<input type="hidden" class="pagerinfo" data-rowcount="@Model.RowCount" data-pagesize="@Model.PageSize"
       data-pageindex="@Model.PageIndex" data-pagecount="@Model.PageCount"
       data-orderfield="@Model.OrderField" data-orderway="@Model.OrderWay" />
<table>
    <thead>
        <tr>
            @foreach (System.Data.DataRow row in Model.showColumn.Rows)
            {
                string colName = row["fieldCode"].ToString();
                if (row["isOrder"].ToString() == "True")
                {
                    <th data-option="@row["optionValue"]" data-field="@row["fieldCode"]" data-order="@Model.OrderWay">@row["fieldName"]@Html.orderColumn(Model.OrderField, Model.OrderWay, row["fieldCode"].ToString())</th>
                }
                else
                {
                    <th data-option="@row["optionValue"]">@row["fieldName"]</th>
                }
            }
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.dataTable.Rows.Count; i++)
        {
            string rowID = Model.dataTable.Rows[i]["rowID"].ToString();
            string keyCode = Model.dataTable.Rows[i][Model.keyField].ToString();
            <tr data-code="@keyCode">
                @foreach (System.Data.DataRow row in Model.showColumn.Rows)
                {
                    string colName = row["fieldCode"].ToString();
                    if (colName == "操作")
                    {
                        <td class="opRow">
                            @Html.ActionLink("删除", "Delete", "rbac_ResourceOp", new { rowID = rowID }, new { data_show = rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.Delete), @class = "listDelete" })
                        </td>
                    }
                    else if (colName == "operationCode")
                    {
                        <td>
                            @Html.Hidden("rowIDList", rowID)
                            @Html.TextBox("operationCodeList", Model.dataTable.Rows[i][colName])
                        </td>
                    }
                    else if (colName == "operationName")
                    {
                        <td>
                            @Html.TextBox("operationNameList", Model.dataTable.Rows[i][colName])
                        </td>
                    }
                    else if (colName == "showOrder")
                    {
                        <td>
                            @Html.TextBox("showOrderList", Model.dataTable.Rows[i][colName])
                        </td>
                    }
                    else
                    {
                        <td>@Model.dataTable.Rows[i][colName]</td >
                    }
                }
            </tr>
        }
    </tbody>
</table>